[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10

[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[sample]]
  name = "Services"
  pageRef = "/services/"
  weight = 30

[[sample]]
  name = "Quality engineering"
  pageRef = "/services/quality engineering/"
  parent = "Services"
  weight = 1

[[sample]]
  name = "Accessibility audit"
  pageRef = "/services/accessibility-audit/"
  parent = "Services"
  weight = 2

[[sample]]
  name = "Testing on-demand"
  pageRef = "/services/testing-on-demand/"
  parent = "Services"
  weight = 2

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

# toml-docs-end sample-navigation