[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Services"
  pageRef = "/services/"
  weight = 20

[[sample]]
  name = "Quality engineering"
  pageRef = "/services/quality engineering/"
  parent = "Services"
  weight = 1

[[sample]]
  name = "Accessibility audit"
  pageRef = "/services/accessibility-audit/"
  parent = "Services"
  weight = 2

[[sample]]
  name = "Testing on-demand"
  pageRef = "/services/testing-on-demand/"
  parent = "Services"
  weight = 2

# toml-docs-end sample-navigation